---
- name: Install Iptables
  package:
    name: iptables
    state: present

- name: Create rules folder
  file:
    path: "{{ iptables_rules_path }}"
    state: directory
    mode: 0775

- name: Deploy rules file
  template:
    src: "iptables-rules.j2"
    dest: "{{ iptables_rules_path }}/iptables-rules"
    mode: 0644
    owner: root
  notify: Restart iptables

- name: Copy systemd unit file
  template:
    src: "iptables-restore.service.j2"
    dest: "/etc/systemd/system/iptables-restore.service"
    owner: "root"
    group: "root"
    mode: "0644"
    
- name: systemd daemon-reload
  systemd:
    daemon_reload: yes
...
