---
- name: Install Iptables
  package:
    name: iptables
    state: present

- name: Create rules folder
  file:
    path: "{{ iptables_rules_path }}"
    state: directory
    mode: 0775

- name: Deploy rules file
  template:
    src: "iptables-rules.bash.j2"
    dest: "{{ iptables_rules_path }}/iptables-rules"
    mode: 0744
    owner: root
  notify: Restart iptables

 - name: Copy firewall init script into place.
   template:
    src: iptables.init.j2
    dest: /etc/init.d/iptables
    owner: root
    group: root
    mode: 0755
  when: "ansible_service_mgr != 'systemd'"

- name: Copy systemd unit file (systemd)
  template:
    src: "iptables.service.j2"
    dest: "/etc/systemd/system/iptables.service"
    owner: "root"
    group: "root"
    mode: "0644"
  when: "ansible_service_mgr == 'systemd'"

- name: systemd daemon-reload (sytemd)
  systemd:
    daemon_reload: true
  when: "ansible_service_mgr == 'systemd'"
...
