---
- name: Installation d'IPtables
  package:
    name: iptables
    state: present

- name: Créer dossier contenant les règles
  file:
    path: "{{ iptables_rules_path }}"
    state: directory
    mode: 0775

- name: Déploiement des règles
  template:
    src: "iptables-rules.j2"
    dest: "{{ iptables_rules_path }}/iptables-rules"
    mode: 0644
    owner: root
  notify: Redemarrage du Firewall

- name: Copy systemd unit file
  template:
    src: "iptables-restore.service.j2"
    dest: "/etc/systemd/system/iptables-restore.service"
    owner: "root"
    group: "root"
    mode: "0644"
  notify: Rechargement de systemd daemon

...